// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         stream_id: 1
 *     }
 */
export interface StopStreamV1StreamStreamIdStopGetRequest {
    stream_id: number;
    run_id?: number | null;
}
