// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         prompt: "prompt"
 *     }
 */
export interface CreateTextToAudioRequestPayload {
    run_id?: number | null;
    traceparent?: string | null;
    project_name?: string | null;
    project_description?: string | null;
    folder_id?: number | null;
    /** The text to be converted to audio. */
    prompt: string;
    /** The desired duration of the audio. */
    duration?: number;
    /** The audio type preference. */
    audio_type?: CambApi.TextToAudioType;
}
