// This file was auto-generated by Fern from our API Definition.

export interface GetTextToAudioResultTextToSoundResultRunIdGetRequest {
    run_id: number | null;
    /** Output format for the Text To Speech result */
    output_type?: string;
}
