// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";
import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         file: fs.createReadStream("/path/to/your/file"),
 *         source_language: 1
 *     }
 */
export interface BodyCreateStoryStoryPost {
    run_id?: number | null;
    /** Text File or Word Document (Docx) for Creating a Story. */
    file: core.file.Uploadable;
    source_language: CambApi.Languages;
    title?: string | null;
    description?: string | null;
    narrator_voice_id?: number | null;
    folder_id?: number | null;
    chosen_dictionaries?: number[] | null;
}
