// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         run_id: 1
 *     }
 */
export interface GetStoryRunInfoStoryResultRunIdGetRequest {
    run_id: number | null;
    /** Whether to include the transcription in the response for fetching the result of a Stories run. */
    include_transcript?: boolean | null;
}
