// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         text: "text",
 *         voice_description: "voice_description"
 *     }
 */
export interface CreateTextToVoiceRequestPayload {
    traceparent?: string | null;
    project_name?: string | null;
    project_description?: string | null;
    folder_id?: number | null;
    /** The text to be converted to voice */
    text: string;
    /** Description to use for the created voice */
    voice_description: string;
}
