// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         run_id: 1,
 *         language: 1,
 *         output_format: "flac"
 *     }
 */
export interface DubbedOutputInAltFormatRequestPayload {
    run_id: number | null;
    language: CambApi.Languages;
    output_format: DubbedOutputInAltFormatRequestPayload.OutputFormat;
}

export namespace DubbedOutputInAltFormatRequestPayload {
    export type OutputFormat = CambApi.AudioOutputType | CambApi.VideoOutputTypeWithoutAvi;
}
