// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         video_url: "video_url",
 *         source_language: 1
 *     }
 */
export interface EndToEndDubbingRequestPayload {
    run_id?: number | null;
    project_name?: string | null;
    project_description?: string | null;
    folder_id?: number | null;
    video_url: string;
    source_language: CambApi.Languages;
    target_language?: CambApi.Languages | null;
    target_languages?: CambApi.Languages[] | null;
    selected_audio_tracks?: number[] | null;
    add_output_as_an_audio_track?: boolean | null;
    chosen_dictionaries?: number[] | null;
    ai_optimization?: boolean | null;
}
