// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         run_id: 1,
 *         language: 1
 *     }
 */
export interface GetDubbedRunTranscriptTranscriptRunIdLanguageGetRequest {
    run_id: number | null;
    language: CambApi.Languages;
    /** Format to use for the transcription. Either `srt`, `vtt` or `txt`. Defaults to `txt`. */
    format_type?: CambApi.TranscriptFileFormat;
    /** Data type for the transcription being returned. Returns the raw data of the transcription or a presigned url for the file that holds the transcription data. */
    data_type?: CambApi.TranscriptDataType;
}
