// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";
import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         file: fs.createReadStream("/path/to/your/file"),
 *         voice_name: "voice_name",
 *         gender: 1
 *     }
 */
export interface BodyCreateCustomVoiceCreateCustomVoicePost {
    run_id?: number | null;
    voice_name: string;
    gender: CambApi.Gender;
    description?: string | null;
    /** By setting true, you consent to making this voice available for other users in the marketplace. */
    publish_voice_to_market_place?: boolean | null;
    age?: number;
    /** Language of the voice */
    language?: CambApi.Languages | null;
    /** Enables advanced audio processing to enhance the clarity and quality of the cloned voice output. When set to `true`, additional processing is applied to improve the overall sound experience. */
    enhance_audio?: boolean | null;
    /** Voice reference file */
    file: core.file.Uploadable;
}
