// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         dictionary_file: fs.createReadStream("/path/to/your/file"),
 *         dictionary_name: "dictionary_name"
 *     }
 */
export interface BodyCreateDictionaryFromFileDictionariesCreateFromFilePost {
    run_id?: number | null;
    /** CSV or Excel Sheet Matching the required structure for a dictionary. */
    dictionary_file: core.file.Uploadable;
    /** The name of the dictonary to be created. This is mainly used for organizational purposes. */
    dictionary_name: string;
    /** The description of the dictionary to be created. This is an optional field that is used to help you provide some info about your dictionaries for better organization. */
    dictionary_description?: string | null;
}
