// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         dictionary_id: 1
 *     }
 */
export interface DeleteDictionaryDictionariesDictionaryIdDeleteRequest {
    dictionary_id: number;
    run_id?: number | null;
}
