// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         dictionary_id: 1,
 *         term_id: 1
 *     }
 */
export interface DeleteDictionaryTermDictionariesTermDictionaryIdTermIdDeleteRequest {
    dictionary_id: number;
    term_id: number;
    run_id?: number | null;
}
