// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         dictionary_id: 1
 *     }
 */
export interface GetDictionaryDetailsDictionariesDictionaryIdFullDetailsGetRequest {
    dictionary_id: number;
    /** Limit how many terms are returned when fetching the dictionary details. */
    limit?: number | null;
    search_term?: string | null;
    run_id?: number | null;
}
