// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         dictionary_id: 1,
 *         term_id: 1,
 *         translations: [{
 *                 translation: "translation",
 *                 language: 1
 *             }]
 *     }
 */
export interface UpdateTermTranslationsPayload {
    dictionary_id: number;
    term_id: number;
    run_id?: number | null;
    translations: CambApi.TermTranslationInput[];
}
