// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         run_id: 1,
 *         target_language: 1
 *     }
 */
export interface CreateTranslationForExistingStoryRequestPayload {
    run_id: number | null;
    target_language: CambApi.Languages;
}
