// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         run_id: 1,
 *         target_language: 1
 *     }
 */
export interface GetTranslatedStoryRunInfoTranslatedStoryResultRunIdTargetLanguageGetRequest {
    run_id: number | null;
    target_language: CambApi.Languages;
    /** Whether to include the transcription in the response for fetching the result of a Stories Translation run. */
    include_transcript?: boolean | null;
}
