// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         texts: ["texts"],
 *         source_language: 1,
 *         target_language: 1
 *     }
 */
export interface CreateTranslationRequestPayload {
    run_id?: number | null;
    project_name?: string | null;
    project_description?: string | null;
    folder_id?: number | null;
    texts: string[];
    age?: number;
    formality?: CambApi.Formalities;
    gender?: CambApi.Gender;
    source_language: CambApi.Languages;
    target_language: CambApi.Languages;
    chosen_dictionaries?: number[] | null;
}
