// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         source_language: 1,
 *         target_language: 1,
 *         text: "text"
 *     }
 */
export interface CreateTranslationStreamRequestPayload {
    traceparent?: string | null;
    source_language: CambApi.Languages;
    target_language: CambApi.Languages;
    text: string;
    formality?: CambApi.Formalities | null;
    gender?: CambApi.Gender | null;
    team_id?: number | null;
    project_name?: string | null;
    project_description?: string | null;
    folder_id?: number | null;
}
