// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as CambApi from "../../../index.js";

export declare namespace ProjectSetupClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ProjectSetupClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ProjectSetupClient.Options>;

    constructor(options: ProjectSetupClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Creates a new project setup with transcription capabilities.
     *
     * This endpoint allows users to create a new project by providing media content
     * (either as a file upload or URL), specifying source and target languages, and
     * other project metadata. The function validates inputs, checks file size limitations,
     * and initiates the project setup process.
     *
     * Args:
     *     request_payload (CreateProjectSetupRequestPayload): Complete project configuration
     *             including media URL, source/target languages, project metadata, and
     *             processing preferences such as audio track selection and dictionary choices.
     *         api_key_obj_and_subscription: Dependency injection providing validated API key
     *             object and associated subscription details for authorization and usage
     *             limit enforcement.
     *         traceparent (str | None, optional): OpenTelemetry trace parent header for
     *             distributed tracing across microservices. Enables request correlation
     *             and performance monitoring throughout the processing pipeline.
     *
     * Returns:
     *     Project setup response with project details and processing status.
     *
     * Raises:
     *     HTTPException:
     *         - 400: If neither media_file nor media_url is provided
     *         - 400: If uploaded file has no filename
     *         - 413: If uploaded file exceeds size limit
     *
     * @param {CambApi.CreateProjectSetupRequestPayload} request
     * @param {ProjectSetupClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.projectSetup.createProject({
     *         media_url: "media_url",
     *         source_language: 1,
     *         target_languages: [1]
     *     })
     */
    public createProject(
        request: CambApi.CreateProjectSetupRequestPayload,
        requestOptions?: ProjectSetupClient.RequestOptions,
    ): core.HttpResponsePromise<CambApi.CreateProjectSetupOut> {
        return core.HttpResponsePromise.fromPromise(this.__createProject(request, requestOptions));
    }

    private async __createProject(
        request: CambApi.CreateProjectSetupRequestPayload,
        requestOptions?: ProjectSetupClient.RequestOptions,
    ): Promise<core.WithRawResponse<CambApi.CreateProjectSetupOut>> {
        const { run_id: runId, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (runId !== undefined) {
            _queryParams.run_id = runId?.toString() ?? null;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CambApiEnvironment.Default,
                "project-setup",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CambApi.CreateProjectSetupOut, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/project-setup");
    }

    /**
     * @param {CambApi.CreateProjectSetupTaskStatusProjectSetupTaskIdGetRequest} request
     * @param {ProjectSetupClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.projectSetup.createProjectSetupTaskStatus({
     *         task_id: "task_id"
     *     })
     */
    public createProjectSetupTaskStatus(
        request: CambApi.CreateProjectSetupTaskStatusProjectSetupTaskIdGetRequest,
        requestOptions?: ProjectSetupClient.RequestOptions,
    ): core.HttpResponsePromise<CambApi.GetCreateProjectSetupResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__createProjectSetupTaskStatus(request, requestOptions));
    }

    private async __createProjectSetupTaskStatus(
        request: CambApi.CreateProjectSetupTaskStatusProjectSetupTaskIdGetRequest,
        requestOptions?: ProjectSetupClient.RequestOptions,
    ): Promise<core.WithRawResponse<CambApi.GetCreateProjectSetupResponse[]>> {
        const { task_id: taskId, run_id: runId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (runId !== undefined) {
            _queryParams.run_id = runId?.toString() ?? null;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CambApiEnvironment.Default,
                `project-setup/${core.url.encodePathParam(taskId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CambApi.GetCreateProjectSetupResponse[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/project-setup/{task_id}");
    }

    /**
     * Retrieves the final result of a completed project setup.
     *
     * This endpoint provides access to the final results of a completed project setup.
     * It verifies that the authenticated user has access to the requested run_id and
     * validates that the run is of the correct type (`DUB_PROJECT`) before returning results.
     *
     * Note:
     *     This endpoint should only be called by users to retrieve their run results via API.
     *     Access validation is performed to ensure users can only access their own runs.
     *
     * Args:
     *     run_id: Positive integer ID of the project setup run.
     *     api_key_obj: API key authentication data from dependency.
     *     traceparent: OpenTelemetry trace header for distributed tracing.
     *
     * Returns:
     *     GetCreateProjectSetupResponse: Project setup results including run details.
     *
     * Raises:
     *     HTTPException:
     *         - 404: If the run_id is not found
     *         - 400: If the run type is not valid for this endpoint (must be DUB_PROJECT)
     *
     * @param {CambApi.GetProjectSetupResultProjectSetupResultRunIdGetRequest} request
     * @param {ProjectSetupClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.projectSetup.getProjectSetupResult({
     *         run_id: 1
     *     })
     */
    public getProjectSetupResult(
        request: CambApi.GetProjectSetupResultProjectSetupResultRunIdGetRequest,
        requestOptions?: ProjectSetupClient.RequestOptions,
    ): core.HttpResponsePromise<CambApi.GetCreateProjectSetupResponse | null> {
        return core.HttpResponsePromise.fromPromise(this.__getProjectSetupResult(request, requestOptions));
    }

    private async __getProjectSetupResult(
        request: CambApi.GetProjectSetupResultProjectSetupResultRunIdGetRequest,
        requestOptions?: ProjectSetupClient.RequestOptions,
    ): Promise<core.WithRawResponse<CambApi.GetCreateProjectSetupResponse | null>> {
        const { run_id: runId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CambApiEnvironment.Default,
                `project-setup-result/${core.url.encodePathParam(runId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CambApi.GetCreateProjectSetupResponse | null,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/project-setup-result/{run_id}",
        );
    }

    /**
     * @param {CambApi.GetProjectSetupRunsResultsProjectSetupResultsPostRequest} request
     * @param {ProjectSetupClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.projectSetup.getProjectSetupRunsResults({
     *         body: {
     *             run_ids: [1]
     *         }
     *     })
     */
    public getProjectSetupRunsResults(
        request: CambApi.GetProjectSetupRunsResultsProjectSetupResultsPostRequest,
        requestOptions?: ProjectSetupClient.RequestOptions,
    ): core.HttpResponsePromise<CambApi.GetCreateProjectSetupResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__getProjectSetupRunsResults(request, requestOptions));
    }

    private async __getProjectSetupRunsResults(
        request: CambApi.GetProjectSetupRunsResultsProjectSetupResultsPostRequest,
        requestOptions?: ProjectSetupClient.RequestOptions,
    ): Promise<core.WithRawResponse<CambApi.GetCreateProjectSetupResponse[]>> {
        const { run_id: runId, body: _body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (runId !== undefined) {
            _queryParams.run_id = runId?.toString() ?? null;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CambApiEnvironment.Default,
                "project-setup-results",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CambApi.GetCreateProjectSetupResponse[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/project-setup-results");
    }
}
