// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as CambApi from "../../../index.js";
import { basetenTts } from "../providers/baseten.js";
import { vertexTts } from "../providers/vertex.js";

export declare namespace TextToSpeechClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions { }
}

export class TextToSpeechClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TextToSpeechClient.Options>;

    constructor(options: TextToSpeechClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @throws {@link CambApi.UnprocessableEntityError}
     */
    public tts(
        request: CambApi.CreateStreamTtsRequestPayload,
        requestOptions?: TextToSpeechClient.RequestOptions,
    ): core.HttpResponsePromise<core.BinaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__tts(request, requestOptions));
    }

    private async __tts(
        request: CambApi.CreateStreamTtsRequestPayload,
        requestOptions?: TextToSpeechClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.BinaryResponse>> {
        // Get provider config from options
        const ttsProvider = (this._options as any).ttsProvider;
        const providerParams = (this._options as any).providerParams;

        // Validate voice_id requirement for default provider
        if (!ttsProvider && !request.voice_id) {
            throw new Error("voice_id is required when using the default Camb.ai provider.");
        }

        // Route to custom provider if configured
        if (ttsProvider === "baseten") {
            return basetenTts(request as any, providerParams, requestOptions);
        }

        if (ttsProvider === "vertex") {
            return vertexTts(request, providerParams, requestOptions);
        }

        // Default Camb.ai provider
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.CambApiEnvironment.Default,
                "tts-stream",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            responseType: "binary-response",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/tts-stream");
    }

    /**
     * @param {CambApi.CreateTtsRequestPayload} request
     * @param {TextToSpeechClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.textToSpeech.createTts({
     *         text: "text",
     *         voice_id: 1,
     *         language: 1
     *     })
     */
    public createTts(
        request: CambApi.CreateTtsRequestPayload,
        requestOptions?: TextToSpeechClient.RequestOptions,
    ): core.HttpResponsePromise<CambApi.CreateTtsOut> {
        return core.HttpResponsePromise.fromPromise(this.__createTts(request, requestOptions));
    }

    private async __createTts(
        request: CambApi.CreateTtsRequestPayload,
        requestOptions?: TextToSpeechClient.RequestOptions,
    ): Promise<core.WithRawResponse<CambApi.CreateTtsOut>> {
        const { run_id: runId, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (runId !== undefined) {
            _queryParams.run_id = runId?.toString() ?? null;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.CambApiEnvironment.Default,
                "tts",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CambApi.CreateTtsOut, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/tts");
    }

    /**
     * @param {CambApi.GetTtsResultTtsTaskIdGetRequest} request
     * @param {TextToSpeechClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.textToSpeech.getTtsResult({
     *         task_id: "task_id"
     *     })
     */
    public getTtsResult(
        request: CambApi.GetTtsResultTtsTaskIdGetRequest,
        requestOptions?: TextToSpeechClient.RequestOptions,
    ): core.HttpResponsePromise<CambApi.OrchestratorPipelineResult> {
        return core.HttpResponsePromise.fromPromise(this.__getTtsResult(request, requestOptions));
    }

    private async __getTtsResult(
        request: CambApi.GetTtsResultTtsTaskIdGetRequest,
        requestOptions?: TextToSpeechClient.RequestOptions,
    ): Promise<core.WithRawResponse<CambApi.OrchestratorPipelineResult>> {
        const { task_id: taskId, run_id: runId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (runId !== undefined) {
            _queryParams.run_id = runId?.toString() ?? null;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.CambApiEnvironment.Default,
                `tts/${core.url.encodePathParam(taskId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CambApi.OrchestratorPipelineResult, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/tts/{task_id}");
    }

    /**
     * Retrieves the result of a Text To Speech (TTS) run.
     *
     * This endpoint validates the provided `run_id` and fetches the corresponding TTS-generated audio.
     * The user must have valid access to the run. The function supports two output formats:
     * - `RAW_BYTES`: Streams the audio file directly.
     * - `FILE_URL`: Returns a pre-signed URL to download the audio file.
     *
     * Args:
     *     run_id (int): Unique identifier for the TTS run.
     *     api_key_obj (dict): API key object used for authentication and storage preferences.
     *     traceparent (Optional[str]): Traceparent header for distributed tracing.
     *     output_type (OutputType, optional): Determines the output format. Defaults to `RAW_BYTES`.
     *
     * Returns:
     *     StreamingResponse | GetTTSOut:
     *         - If `output_type = RAW_BYTES`: A streaming response containing the TTS-generated audio in FLAC format.
     *         - If `output_type = FILE_URL`: A URL pointing to the stored TTS-generated audio file.
     *
     * Raises:
     *     HTTPException:
     *         - 400 BAD REQUEST if the run ID is invalid or does not belong to a TTS process.
     *         - 500 INTERNAL SERVER ERROR if fetching or streaming the audio fails.
     *
     * Assumptions:
     *     - The user has valid access to the `run_id`.
     *     - The `run_id` corresponds to a valid TTS run.
     *     - There is only **one** dialogue associated with the given `run_id`.
     *
     * @param {CambApi.GetTtsRunInfoTtsResultRunIdGetRequest} request
     * @param {TextToSpeechClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.textToSpeech.getTtsRunInfo({
     *         run_id: 1
     *     })
     */
    public getTtsRunInfo(
        request: CambApi.GetTtsRunInfoTtsResultRunIdGetRequest,
        requestOptions?: TextToSpeechClient.RequestOptions,
    ): core.HttpResponsePromise<CambApi.GetTtsRunInfoTtsResultRunIdGetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTtsRunInfo(request, requestOptions));
    }

    private async __getTtsRunInfo(
        request: CambApi.GetTtsRunInfoTtsResultRunIdGetRequest,
        requestOptions?: TextToSpeechClient.RequestOptions,
    ): Promise<core.WithRawResponse<CambApi.GetTtsRunInfoTtsResultRunIdGetResponse>> {
        const { run_id: runId, output_type: outputType } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (outputType != null) {
            _queryParams.output_type = outputType;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.CambApiEnvironment.Default,
                `tts-result/${core.url.encodePathParam(runId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CambApi.GetTtsRunInfoTtsResultRunIdGetResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/tts-result/{run_id}");
    }

    /**
     * @param {CambApi.GetTtsResultsTtsResultsPostRequest} request
     * @param {TextToSpeechClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.textToSpeech.getTtsResults({
     *         body: {
     *             run_ids: [1]
     *         }
     *     })
     */
    public getTtsResults(
        request: CambApi.GetTtsResultsTtsResultsPostRequest,
        requestOptions?: TextToSpeechClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__getTtsResults(request, requestOptions));
    }

    private async __getTtsResults(
        request: CambApi.GetTtsResultsTtsResultsPostRequest,
        requestOptions?: TextToSpeechClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { run_id: runId, traceparent, body: _body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (runId !== undefined) {
            _queryParams.run_id = runId?.toString() ?? null;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ traceparent: traceparent !== undefined ? traceparent : undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.CambApiEnvironment.Default,
                "tts-results",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Record<string, unknown>,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/tts-results");
    }

    /**
     * @param {CambApi.GetTtsResultDiscordDiscordTtsTaskIdGetRequest} request
     * @param {TextToSpeechClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.textToSpeech.getTtsResultDiscord({
     *         task_id: "task_id"
     *     })
     */
    public getTtsResultDiscord(
        request: CambApi.GetTtsResultDiscordDiscordTtsTaskIdGetRequest,
        requestOptions?: TextToSpeechClient.RequestOptions,
    ): core.HttpResponsePromise<CambApi.OrchestratorPipelineResult> {
        return core.HttpResponsePromise.fromPromise(this.__getTtsResultDiscord(request, requestOptions));
    }

    private async __getTtsResultDiscord(
        request: CambApi.GetTtsResultDiscordDiscordTtsTaskIdGetRequest,
        requestOptions?: TextToSpeechClient.RequestOptions,
    ): Promise<core.WithRawResponse<CambApi.OrchestratorPipelineResult>> {
        const { task_id: taskId, run_id: runId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (runId !== undefined) {
            _queryParams.run_id = runId?.toString() ?? null;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                (await core.Supplier.get(this._options.environment)) ??
                environments.CambApiEnvironment.Default,
                `discord/tts/${core.url.encodePathParam(taskId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CambApi.OrchestratorPipelineResult, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/discord/tts/{task_id}");
    }
}
