// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         text: "text",
 *         voice_id: 1,
 *         language: 1
 *     }
 */
export interface CreateTtsRequestPayload {
    run_id?: number | null;
    project_name?: string | null;
    project_description?: string | null;
    folder_id?: number | null;
    text: string;
    voice_id: number;
    language: CambApi.Languages;
    gender?: CambApi.Gender;
    age?: number | null;
}
