// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         task_id: "task_id"
 *     }
 */
export interface GetTtsResultDiscordDiscordTtsTaskIdGetRequest {
    task_id: string;
    run_id?: number | null;
}
