// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         run_id: 1
 *     }
 */
export interface GetTtsRunInfoTtsResultRunIdGetRequest {
    run_id: number | null;
    /** Output format for the Text To Speech result */
    output_type?: string;
}
