// This file was auto-generated by Fern from our API Definition.

export const AudioOutputType = {
    Flac: "flac",
    Wav: "wav",
    Mp3: "mp3",
    Aac: "aac",
    M4A: "m4a",
} as const;
export type AudioOutputType = (typeof AudioOutputType)[keyof typeof AudioOutputType];
