// This file was auto-generated by Fern from our API Definition.

export interface AudioStream {
    index: number;
    codec_name: string;
    codec_long_name: string;
    codec_tag_string?: string | null;
    codec_tag?: string | null;
    profile?: string | null;
    sample_fmt: string;
    sample_rate: number;
    channels: number;
    channel_layout?: string | null;
    id?: string | null;
    bit_rate?: number;
    tags?: Record<string, unknown> | null;
}
