// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface ConfigStreamPipeline {
    demixing?: CambApi.DemixingOption;
    segmenting?: CambApi.SegmentingOption;
    transcribing?: CambApi.TranscribingOption;
    translating?: CambApi.TranslatingOption;
    revoicing?: CambApi.RevoicingOption;
}
