// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface CreateStreamRequestPayload {
    /** The name of the stream. */
    name?: string | null;
    /** The description of the stream. */
    description?: string | null;
    /** The initial delay in seconds before starting the stream creation process. */
    initial_delay?: number;
    /** The maximum duration in minutes for the stream creation process before timing out. */
    timeout_in_mins?: number | null;
    /** List of voice identifiers to be used in the stream. */
    voices?: number[];
    /** List of dictionary identifiers to be used in the stream. */
    dictionaries?: number[];
    /** The shared configuration for the streaming pipeline. */
    config?: CambApi.ConfigStream;
    /** The source stream configuration details. */
    source_stream: CambApi.SourceStream;
    /** List of target stream configurations. */
    target_streams: CambApi.TargetStream[];
    start_time?: string | null;
    end_time?: string | null;
    timezone?: string | null;
}
