// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface CreateStreamOut {
    stream_id: number;
    stream_url_for_languages: CambApi.StreamUrlForLanguages[];
    task_id: string;
}
