// This file was auto-generated by Fern from our API Definition.

export interface DataStream {
    index: number;
    codec_name?: string | null;
    codec_long_name?: string | null;
    codec_tag_string?: string | null;
    codec_tag?: string | null;
    id?: string | null;
}
