// This file was auto-generated by Fern from our API Definition.

export const DemixingOption = {
    None: "none",
    PickLeftChannel: "pick_left_channel",
    PickRightChannel: "pick_right_channel",
    PickCenterChannel: "pick_center_channel",
    BestModel: "best_model",
    FastModel: "fast_model",
} as const;
export type DemixingOption = (typeof DemixingOption)[keyof typeof DemixingOption];
