// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface DictionaryWithTerms {
    id: number;
    name: string;
    description?: string | null;
    created_at?: string | null;
    last_edited_at?: string | null;
    dictionary_terms?: CambApi.DictionaryTerm[] | null;
    languages?: CambApi.Languages[] | null;
}
