// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface DictionaryTerm {
    id: number;
    term_translations: CambApi.TermTranslationOutput[];
}
