// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface DubbingResult {
    audio_url: string;
    transcript: CambApi.Transcript[];
    video_url?: string | null;
}
