// This file was auto-generated by Fern from our API Definition.

export const ExceptionReasons = {
    HarmfulContentDetected: "HARMFUL_CONTENT_DETECTED",
    VoiceConversionError: "VOICE_CONVERSION_ERROR",
    ProcessingError: "PROCESSING_ERROR",
    SourceTooLong: "SOURCE_TOO_LONG",
    SourceTooLarge: "SOURCE_TOO_LARGE",
    SourceTypeNotSupported: "SOURCE_TYPE_NOT_SUPPORTED",
    ErrorDownloadingSource: "ERROR_DOWNLOADING_SOURCE",
    TooManyGdriveRequests: "TOO_MANY_GDRIVE_REQUESTS",
    SourceBlockedInRegion: "SOURCE_BLOCKED_IN_REGION",
    SourceIsAgeRestricted: "SOURCE_IS_AGE_RESTRICTED",
    SourceNotFound: "SOURCE_NOT_FOUND",
    MismatchedSourceCodec: "MISMATCHED_SOURCE_CODEC",
    ContentDoesNotMatchExtension: "CONTENT_DOES_NOT_MATCH_EXTENSION",
    InvalidSourceData: "INVALID_SOURCE_DATA",
    VideoDoesNotHaveAudioStreams: "VIDEO_DOES_NOT_HAVE_AUDIO_STREAMS",
    MasteringOutOfRange: "MASTERING_OUT_OF_RANGE",
    InvalidAudioTracksSelection: "INVALID_AUDIO_TRACKS_SELECTION",
    PaymentRequired: "PAYMENT_REQUIRED",
    Forbidden: "FORBIDDEN",
    InternalError: "INTERNAL_ERROR",
    None: "NONE",
} as const;
export type ExceptionReasons = (typeof ExceptionReasons)[keyof typeof ExceptionReasons];
