// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface GetCreateProjectSetupResponse {
    run_id: number;
    project_details: CambApi.ProjectDetails;
}
