// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface GetProbeStreamOut {
    video_streams: CambApi.VideoStream[];
    audio_streams: CambApi.AudioStream[];
    data_streams: CambApi.DataStream[];
}
