// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface GetSetupStoryResultResponse {
    run_id: number;
    story_details: CambApi.StoryDetails;
}
