// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface OrchestratorPipelineResult {
    status: CambApi.TaskStatus;
    run_id?: number | null;
    exception_reason?: OrchestratorPipelineResult.ExceptionReason | null;
    message?: OrchestratorPipelineResult.Message | null;
}

export namespace OrchestratorPipelineResult {
    export type ExceptionReason = string | CambApi.ExceptionReasons;
    export type Message = Record<string, unknown> | string;
}
