// This file was auto-generated by Fern from our API Definition.

export const OutputFormat = {
    Wav: "wav",
    Flac: "flac",
    Adts: "adts",
    Mp3: "mp3",
    PcmS16Le: "pcm_s16le",
    PcmS16Be: "pcm_s16be",
    PcmS32Be: "pcm_s32be",
    PcmS32Le: "pcm_s32le",
    PcmF32Le: "pcm_f32le",
    PcmF32Be: "pcm_f32be",
} as const;
export type OutputFormat = (typeof OutputFormat)[keyof typeof OutputFormat];
