// This file was auto-generated by Fern from our API Definition.

export interface OverdubConfig {
    /** Proportion of the original audio (0.0 to 1.0). */
    original_audio_gain?: number | null;
    /** Proportion of the background audio (0.0 to 1.0). */
    background_audio_gain?: number | null;
    /** Cross-fade duration in seconds (0.0 to 5.0). */
    fade_time?: number;
    /** Proportion of the fallback audio (0.0 to 1.0) (for streaming only). */
    fallback_audio_gain?: number | null;
}
