// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface ProjectDetails {
    project_name: string;
    project_description?: string | null;
    created_at: string;
    source_language: CambApi.Languages;
    target_languages: CambApi.Languages[];
    duration?: number | null;
    folder_id?: number | null;
    studio_url: string;
}
