// This file was auto-generated by Fern from our API Definition.

export const RevoicingOption = {
    None: "none",
    BestModel: "best_model",
    FastModel: "fast_model",
} as const;
export type RevoicingOption = (typeof RevoicingOption)[keyof typeof RevoicingOption];
