// This file was auto-generated by Fern from our API Definition.

export const SegmentingOption = {
    None: "none",
    Loudness: "loudness",
    BestModel: "best_model",
    FastModel: "fast_model",
} as const;
export type SegmentingOption = (typeof SegmentingOption)[keyof typeof SegmentingOption];
