// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface SourceStream {
    language: CambApi.Languages;
    url: string;
    category?: CambApi.StreamCategory | null;
    passphrase?: string | null;
    streamid?: string | null;
    number_of_streams?: number | null;
    audio_stream?: number | null;
    background_audio_stream?: number | null;
    latency?: number | null;
    relay_input?: boolean | null;
}
