// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface StoryDetails {
    story_title: string;
    story_description?: string | null;
    created_at: string;
    source_language: CambApi.Languages;
    target_languages?: CambApi.Languages[] | null;
    folder_id?: number | null;
    studio_url: string;
}
