// This file was auto-generated by Fern from our API Definition.

/**
 * Advanced settings for voice customization.
 *
 * Attributes:
 *     enhance_reference_audio_quality: Whether to enhance the quality of the
 *         reference audio before cloning. Defaults to False.
 */
export interface StreamTtsVoiceSettings {
    enhance_reference_audio_quality?: boolean | null;
    maintain_source_accent?: boolean | null;
    apply_ref_loudness_norm?: boolean | null;
}
