// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

/**
 * Configuration for the output audio of Streaming TTS.
 *
 * Attributes:
 *     format: The format of the output audio. Defaults to MP3.
 *     duration: The desired duration of the output audio in seconds. If not
 *         provided, it will be determined automatically.
 *     apply_enhancement: Whether to apply audio enhancement to the output.
 *         Defaults to True.
 */
export interface StreamTtsOutputConfiguration {
    format?: CambApi.OutputFormat;
    duration?: number | null;
    apply_enhancement?: boolean;
}
