// This file was auto-generated by Fern from our API Definition.

/**
 * Advanced options for controlling the TTS inference process.
 *
 * These options are only supported for the MARS-8 family of speech models.
 *
 * Attributes:
 *     stability: A value between 0.0 and 1.0 that controls the stability of
 *         the output audio.
 *     temperature: A value between 0.01 and 4.0 that controls the randomness
 *         of the output. Higher values mean more randomness.
 *     inference_steps: The number of steps for the diffusion model. A value
 *         between 1 and 1000.
 *     speaker_similarity: A value between 0.0 and 1.0 that controls how
 *         similar the output should be to the reference speaker.
 */
export interface StreamTtsInferenceOptions {
    stability?: number | null;
    temperature?: number | null;
    inference_steps?: number | null;
    speaker_similarity?: number | null;
    localize_speaker_weight?: number | null;
    acoustic_quality_boost?: boolean | null;
}
