// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface TargetStream {
    languages: CambApi.Languages[];
    url: string;
    type: CambApi.StreamType;
    passphrase?: string | null;
    streamid?: string | null;
    pids?: (number | null)[] | null;
    transcode_video?: boolean | null;
    embed_subtitles?: boolean | null;
    audio_codec?: string | null;
    audio_bitrate?: string | null;
    audio_channel_layout?: string | null;
    latency?: number | null;
    constant_bitrate?: boolean | null;
    relay_output?: boolean | null;
}
