// This file was auto-generated by Fern from our API Definition.

export const TaskStatus = {
    Success: "SUCCESS",
    Pending: "PENDING",
    Error: "ERROR",
} as const;
export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];
