// This file was auto-generated by Fern from our API Definition.

export const TextToAudioType = {
    Sound: "sound",
    Music: "music",
} as const;
export type TextToAudioType = (typeof TextToAudioType)[keyof typeof TextToAudioType];
