// This file was auto-generated by Fern from our API Definition.

export const TranscriptFileFormat = {
    Srt: "srt",
    Vtt: "vtt",
    Txt: "txt",
} as const;
export type TranscriptFileFormat = (typeof TranscriptFileFormat)[keyof typeof TranscriptFileFormat];
