// This file was auto-generated by Fern from our API Definition.

export const TranscribingOption = {
    None: "none",
    BestModel: "best_model",
    FastModel: "fast_model",
} as const;
export type TranscribingOption = (typeof TranscribingOption)[keyof typeof TranscribingOption];
