// This file was auto-generated by Fern from our API Definition.

export const TranslatingOption = {
    None: "none",
    BestModel: "best_model",
    FastModel: "fast_model",
} as const;
export type TranslatingOption = (typeof TranslatingOption)[keyof typeof TranslatingOption];
