// This file was auto-generated by Fern from our API Definition.

export const TranscriptDataType = {
    RawData: "raw_data",
    File: "file",
} as const;
export type TranscriptDataType = (typeof TranscriptDataType)[keyof typeof TranscriptDataType];
