// This file was auto-generated by Fern from our API Definition.

export interface VideoStream {
    index: number;
    codec_name: string;
    codec_long_name: string;
    codec_tag_string?: string | null;
    codec_tag?: string | null;
    profile?: string | null;
    width?: number | null;
    height?: number | null;
    is_avc?: boolean | null;
    id?: string | null;
}
