// This file was auto-generated by Fern from our API Definition.

export const VideoOutputTypeWithoutAvi = {
    Mkv: "mkv",
    Mp4: "mp4",
    Mov: "mov",
    Mxf: "mxf",
} as const;
export type VideoOutputTypeWithoutAvi = (typeof VideoOutputTypeWithoutAvi)[keyof typeof VideoOutputTypeWithoutAvi];
