// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../index.js";

export interface Voice {
    id: number;
    voice_name: string;
    gender?: number | null;
    age?: number | null;
    language?: CambApi.Languages | null;
    transcript?: string | null;
    description?: string | null;
    is_published?: boolean | null;
    signed_url?: string | null;
}
