// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             url: "url"
 *         }
 *     }
 */
export interface GetProbeStreamStreamProbePostRequest {
    run_id?: number | null;
    body: CambApi.GetProbeStreamIn;
}
