// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         stream_id: 1
 *     }
 */
export interface UpdateStreamDataRequestPayload {
    stream_id: number;
    run_id?: number | null;
    start_time?: string | null;
    end_time?: string | null;
    payload?: Record<string, unknown> | null;
    target_languages?: CambApi.Languages[] | null;
    timezone?: string | null;
}
