// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         folder_name: "folder_name"
 *     }
 */
export interface CreateFolderPayload {
    run_id?: number | null;
    folder_name: string;
}
