// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListFoldersFoldersGetRequest {
    limit?: number | null;
    search_query?: string | null;
    run_id?: number | null;
}
