// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as CambApi from "../../../index.js";

export declare namespace AudioSeparationClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AudioSeparationClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AudioSeparationClient.Options>;

    constructor(options: AudioSeparationClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {CambApi.BodyCreateAudioSeparationAudioSeparationPost} request
     * @param {AudioSeparationClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     import { createReadStream } from "fs";
     *     await client.audioSeparation.createAudioSeparation({})
     */
    public createAudioSeparation(
        request: CambApi.BodyCreateAudioSeparationAudioSeparationPost,
        requestOptions?: AudioSeparationClient.RequestOptions,
    ): core.HttpResponsePromise<CambApi.OrchestratorPipelineCallResult> {
        return core.HttpResponsePromise.fromPromise(this.__createAudioSeparation(request, requestOptions));
    }

    private async __createAudioSeparation(
        request: CambApi.BodyCreateAudioSeparationAudioSeparationPost,
        requestOptions?: AudioSeparationClient.RequestOptions,
    ): Promise<core.WithRawResponse<CambApi.OrchestratorPipelineCallResult>> {
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (request.run_id !== undefined) {
            _queryParams.run_id = request.run_id?.toString() ?? null;
        }

        const _request = await core.newFormData();
        if (request.media_file != null) {
            await _request.appendFile("media_file", request.media_file);
        }

        if (request.project_name != null) {
            _request.append("project_name", request.project_name);
        }

        if (request.project_description != null) {
            _request.append("project_description", request.project_description);
        }

        if (request.folder_id != null) {
            _request.append("folder_id", request.folder_id?.toString() ?? null);
        }

        const _maybeEncodedRequest = await _request.getRequest();
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                traceparent: request.traceparent !== undefined ? request.traceparent : undefined,
                ..._maybeEncodedRequest.headers,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CambApiEnvironment.Default,
                "audio-separation",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "file",
            duplex: _maybeEncodedRequest.duplex,
            body: _maybeEncodedRequest.body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CambApi.OrchestratorPipelineCallResult,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/audio-separation");
    }

    /**
     * @param {CambApi.GetAudioSeparationStatusAudioSeparationTaskIdGetRequest} request
     * @param {AudioSeparationClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.audioSeparation.getAudioSeparationStatus({
     *         task_id: "task_id"
     *     })
     */
    public getAudioSeparationStatus(
        request: CambApi.GetAudioSeparationStatusAudioSeparationTaskIdGetRequest,
        requestOptions?: AudioSeparationClient.RequestOptions,
    ): core.HttpResponsePromise<CambApi.OrchestratorPipelineResult> {
        return core.HttpResponsePromise.fromPromise(this.__getAudioSeparationStatus(request, requestOptions));
    }

    private async __getAudioSeparationStatus(
        request: CambApi.GetAudioSeparationStatusAudioSeparationTaskIdGetRequest,
        requestOptions?: AudioSeparationClient.RequestOptions,
    ): Promise<core.WithRawResponse<CambApi.OrchestratorPipelineResult>> {
        const { task_id: taskId, run_id: runId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (runId !== undefined) {
            _queryParams.run_id = runId?.toString() ?? null;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CambApiEnvironment.Default,
                `audio-separation/${core.url.encodePathParam(taskId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CambApi.OrchestratorPipelineResult, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/audio-separation/{task_id}");
    }

    /**
     * @param {CambApi.GetAudioSeparationRunInfoAudioSeparationResultRunIdGetRequest} request
     * @param {AudioSeparationClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.audioSeparation.getAudioSeparationRunInfo({
     *         run_id: 1
     *     })
     */
    public getAudioSeparationRunInfo(
        request: CambApi.GetAudioSeparationRunInfoAudioSeparationResultRunIdGetRequest,
        requestOptions?: AudioSeparationClient.RequestOptions,
    ): core.HttpResponsePromise<CambApi.GetAudioSeparationResultOut> {
        return core.HttpResponsePromise.fromPromise(this.__getAudioSeparationRunInfo(request, requestOptions));
    }

    private async __getAudioSeparationRunInfo(
        request: CambApi.GetAudioSeparationRunInfoAudioSeparationResultRunIdGetRequest,
        requestOptions?: AudioSeparationClient.RequestOptions,
    ): Promise<core.WithRawResponse<CambApi.GetAudioSeparationResultOut>> {
        const { run_id: runId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CambApiEnvironment.Default,
                `audio-separation-result/${core.url.encodePathParam(runId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CambApi.GetAudioSeparationResultOut, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/audio-separation-result/{run_id}",
        );
    }

    /**
     * @param {CambApi.GetAudioSeparationRunsResultsAudioSeparationResultsPostRequest} request
     * @param {AudioSeparationClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.audioSeparation.getAudioSeparationRunsResults({
     *         body: {
     *             run_ids: [1]
     *         }
     *     })
     */
    public getAudioSeparationRunsResults(
        request: CambApi.GetAudioSeparationRunsResultsAudioSeparationResultsPostRequest,
        requestOptions?: AudioSeparationClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, CambApi.GetAudioSeparationResultOut>> {
        return core.HttpResponsePromise.fromPromise(this.__getAudioSeparationRunsResults(request, requestOptions));
    }

    private async __getAudioSeparationRunsResults(
        request: CambApi.GetAudioSeparationRunsResultsAudioSeparationResultsPostRequest,
        requestOptions?: AudioSeparationClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, CambApi.GetAudioSeparationResultOut>>> {
        const { run_id: runId, traceparent, body: _body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (runId !== undefined) {
            _queryParams.run_id = runId?.toString() ?? null;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ traceparent: traceparent !== undefined ? traceparent : undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CambApiEnvironment.Default,
                "audio-separation-results",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Record<string, CambApi.GetAudioSeparationResultOut>,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/audio-separation-results");
    }
}
