// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         text: "text",
 *         voice_id: 1,
 *         source_language: 1,
 *         target_language: 1
 *     }
 */
export interface CreateTranslatedTtsRequestPayload {
    run_id?: number | null;
    traceparent?: string | null;
    project_name?: string | null;
    project_description?: string | null;
    folder_id?: number | null;
    text: string;
    voice_id: number;
    age?: number | null;
    formality?: CambApi.Formalities | null;
    gender?: CambApi.Gender | null;
    source_language: CambApi.Languages;
    target_language: CambApi.Languages;
    chosen_dictionaries?: number[] | null;
}
