// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../index.js";

export type SetupStoryStorySetupPostResponse =
    | CambApi.OrchestratorPipelineCallResult
    | CambApi.GetSetupStoryResultResponse;
