// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as CambApi from "../../../index.js";

export declare namespace LanguagesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class LanguagesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<LanguagesClient.Options>;

    constructor(options: LanguagesClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {CambApi.GetSourceLanguagesSourceLanguagesGetRequest} request
     * @param {LanguagesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.languages.getSourceLanguages()
     */
    public getSourceLanguages(
        request: CambApi.GetSourceLanguagesSourceLanguagesGetRequest = {},
        requestOptions?: LanguagesClient.RequestOptions,
    ): core.HttpResponsePromise<CambApi.LanguagePydanticModel[]> {
        return core.HttpResponsePromise.fromPromise(this.__getSourceLanguages(request, requestOptions));
    }

    private async __getSourceLanguages(
        request: CambApi.GetSourceLanguagesSourceLanguagesGetRequest = {},
        requestOptions?: LanguagesClient.RequestOptions,
    ): Promise<core.WithRawResponse<CambApi.LanguagePydanticModel[]>> {
        const { run_id: runId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (runId !== undefined) {
            _queryParams.run_id = runId?.toString() ?? null;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CambApiEnvironment.Default,
                "source-languages",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CambApi.LanguagePydanticModel[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/source-languages");
    }

    /**
     * @param {CambApi.GetTargetLanguagesTargetLanguagesGetRequest} request
     * @param {LanguagesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CambApi.UnprocessableEntityError}
     *
     * @example
     *     await client.languages.getTargetLanguages()
     */
    public getTargetLanguages(
        request: CambApi.GetTargetLanguagesTargetLanguagesGetRequest = {},
        requestOptions?: LanguagesClient.RequestOptions,
    ): core.HttpResponsePromise<CambApi.LanguagePydanticModel[]> {
        return core.HttpResponsePromise.fromPromise(this.__getTargetLanguages(request, requestOptions));
    }

    private async __getTargetLanguages(
        request: CambApi.GetTargetLanguagesTargetLanguagesGetRequest = {},
        requestOptions?: LanguagesClient.RequestOptions,
    ): Promise<core.WithRawResponse<CambApi.LanguagePydanticModel[]>> {
        const { run_id: runId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (runId !== undefined) {
            _queryParams.run_id = runId?.toString() ?? null;
        }

        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CambApiEnvironment.Default,
                "target-languages",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CambApi.LanguagePydanticModel[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CambApi.UnprocessableEntityError(
                        _response.error.body as CambApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CambApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/target-languages");
    }
}
