// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";
import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         language: 1
 *     }
 */
export interface BodyCreateTranscriptionTranscribePost {
    run_id?: number | null;
    /** Signed URL to audio file for transcription */
    language: CambApi.Languages;
    /** Media file for transcription */
    media_file?: core.file.Uploadable | undefined;
    /** Signed URL to media file for transcription */
    media_url?: string | null;
    /** [DEPRECATED] Use 'file' instead */
    file?: core.file.Uploadable | undefined;
    /** [DEPRECATED] Use 'audio_url' instead */
    audio_url?: string | null;
    project_name?: string | null;
    project_description?: string | null;
    folder_id?: number | null;
}
