// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         run_id: 1
 *     }
 */
export interface GetTranscriptionResultTranscriptionResultRunIdGetRequest {
    run_id: number | null;
    word_level_timestamps?: boolean | null;
}
