// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         media_url: "media_url",
 *         source_language: 1,
 *         target_languages: [1]
 *     }
 */
export interface CreateProjectSetupRequestPayload {
    run_id?: number | null;
    project_name?: string | null;
    project_description?: string | null;
    folder_id?: number | null;
    media_url: string;
    source_language: CambApi.Languages;
    target_languages: CambApi.Languages[];
    selected_audio_tracks?: number[] | null;
    add_output_as_an_audio_track?: boolean | null;
    chosen_dictionaries?: number[];
}
