// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             run_ids: [1]
 *         }
 *     }
 */
export interface GetProjectSetupRunsResultsProjectSetupResultsPostRequest {
    run_id?: number | null;
    body: CambApi.RunIDsRequestPayload;
}
