// This file was auto-generated by Fern from our API Definition.

export const CambApiEnvironment = {
    Default: "https://client.camb.ai/apis",
} as const;

export type CambApiEnvironment = typeof CambApiEnvironment.Default;
