// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

/**
 * @example
 *     {}
 */
export interface BodyCreateAudioSeparationAudioSeparationPost {
    run_id?: number | null;
    traceparent?: string | null;
    /** Audio file for transcription */
    media_file?: core.file.Uploadable | undefined;
    project_name?: string | null;
    project_description?: string | null;
    folder_id?: number | null;
}
