// This file was auto-generated by Fern from our API Definition.

import * as core from "../core/index.js";
import * as errors from "../errors/index.js";

export namespace HeaderAuthProvider {
    export interface AuthOptions {
        apiKey: core.Supplier<string>;
    }

    export interface Options extends AuthOptions {
        ttsProvider?: string;
        providerParams?: Record<string, any>;
    }
}

export class HeaderAuthProvider implements core.AuthProvider {
    private readonly headerValue: core.Supplier<string>;
    private readonly ttsProvider?: string;
    private readonly providerParams?: Record<string, any>;

    constructor(options: HeaderAuthProvider.Options) {
        this.headerValue = options.apiKey;
        this.ttsProvider = options.ttsProvider;
        this.providerParams = options.providerParams;
    }

    public static canCreate(options: HeaderAuthProvider.Options): boolean {
        return options.apiKey != null;
    }

    public async getAuthRequest(_arg?: { endpointMetadata?: core.EndpointMetadata }): Promise<core.AuthRequest> {
        const headers: Record<string, string> = {};

        // Add API key if provided
        const apiKey = await core.Supplier.get(this.headerValue);
        if (apiKey != null) {
            headers["x-api-key"] = apiKey;
        }

        // Add custom provider header if configured
        if (this.ttsProvider) {
            headers["tts_provider"] = this.ttsProvider;
        }

        return { headers };
    }
}
